/**
 * Ultimate Event Provider for Jalali Calendar.
 * Consolidates Persian, Hijri, Gregorian, and International events.
 */

import * as Jalaali from './jalali.js';

function createEvent(title, isHoliday) { return { title, isHoliday }; }

// Consolidated Iranian Events
// Sources: 
// - https://www.farhang.gov.ir/ershad_content/media/image/2020/09/1004261_orig.pdf
const IRANIAN_EVENTS = {
    '1-1': [createEvent('عید نوروز', true)],
    '1-2': [createEvent('عید نوروز', true)],
    '1-3': [createEvent('عید نوروز', true)],
    '1-4': [createEvent('عید نوروز', true)],
    '1-6': [createEvent('ولادت زرتشت', false)],
    '1-7': [createEvent('روز هنرهای نمایشی', false)],
    '1-12': [createEvent('روز جمهوری اسلامی', true)],
    '1-13': [createEvent('روز طبیعت', true)],
    '1-18': [createEvent('روز سلامتی', false)],
    '1-20': [createEvent('روز ملی فناوری هسته‌ای', false)],
    '1-25': [createEvent('روز بزرگداشت عطار نیشابوری', false)],
    '1-29': [createEvent('روز ارتش جمهوری اسلامی و نیروی زمینی', false)],
    '2-1': [createEvent('روز بزرگداشت سعدی', false)],
    '2-3': [createEvent('روز بزرگداشت شیخ بهایی', false),createEvent('روز معماری', false)],
    '2-7': [createEvent('روز ایمنی حمل و نقل', false)],
    '2-9': [createEvent('روز شوراها', false)],
    '2-10': [createEvent('روز ملی خلیج فارس', false)],
    '2-15': [createEvent('روز بزرگداشت شیخ صدوق', false)],
    '2-18': [createEvent('روز بیماری‌های خاص و صعب العلاج', false)],
    '2-19': [createEvent('روز بزرگداشت شیخ کلینی', false)],
    '2-25': [createEvent('روز پاسداشت زبان فارسی و بزرگداشت حکیم ابوالقاسم فردوسی', false)],
    '2-28': [createEvent('روز بزرگداشت حکیم عمر خیام', false)],
    '2-30': [createEvent('روز ملی جمعیت', false)],
    '2-31': [createEvent('روز اهدای عضو، اهدای زندگی', false)],
    '3-1': [createEvent('روز بهره‌وری و بهینه‌سازی مصرف', false),createEvent('روز بزرگداشت ملاصدرا', false)],
    '3-8': [createEvent('روز فرهنگ پهلوانی و ورزش زورخانه‌ای', false)],
    '3-14': [createEvent('رحلت امام خمینی', true)],
    '3-15': [createEvent('قیام خونین 15 خرداد', true)],
    '3-20': [createEvent('روز صنایع دستی', false)],
    '3-29': [createEvent('درگذشت دکتر علی شریعتی', false)],
    '3-31': [createEvent('شهادت دکتر مصطفی چمران', false),createEvent('روز بسیج استادان', false)],
    '4-1': [createEvent('روز اصناف', false)],
    '4-7': [createEvent('روز قوه قضاییه', false)],
    '4-8': [createEvent('روز مبارزه با سلاح‌های شیمیایی و میکروبی', false)],
    '4-10': [createEvent('روز صنعت و معدن', false)],
    '4-14': [createEvent('روز قلم', false)],
    '4-18': [createEvent('روز ادبیات کودکان و نوجوانان', false)],
    '4-23': [createEvent('روز گفت‌وگو و تعامل سازنده با جهان', false)],
    '4-25': [createEvent('روز بهزیستی و تامین اجتماعی', false)],
    '5-9': [createEvent('روز اهدای خون', false)],
    '5-14': [createEvent('روز خانواده و تکریم بازنشستگان', false)],
    '5-17': [createEvent('روز خبرنگار', false)],
    '5-21': [createEvent('روز حمایت از صنایع کوچک', false)],
    '5-22': [createEvent('روز تشکل‌ها و مشارکت‌های اجتماعی', false)],
    '5-23': [createEvent('روز مقاومت اسلامی', false)],
    '5-29': [createEvent('روز تجلیل از اسرا و مفقودان', false)],
    '5-30': [createEvent('روز بزرگداشت علامه مجلسی', false),createEvent('روز جهانی مسجد', false)],
    '6-1': [createEvent('روز بزرگداشت ابوعلی سینا', false),createEvent('روز پزشک', false)],
    '6-4': [createEvent('روز کارمند', false)],
    '6-5': [createEvent('روز بزرگداشت محمدبن‌زکریا رازی', false),createEvent('روز داروسازی', false),createEvent('روز کشتی', false)],
    '6-8': [createEvent('روز مبارزه با تروریسم', false)],
    '6-13': [createEvent('روز بزرگداشت ابوریحان بیرونی', false),createEvent('روز تعاون', false)],
    '6-21': [createEvent('روز سینما', false)],
    '6-23': [createEvent('روز بزرگداشت سلمان فارسی', false)],
    '6-27': [createEvent('روز بزرگداشت شهریار', false),createEvent('روز شعر و ادب فارسی', false)],
    '7-5': [createEvent('روز گردشگری', false)],
    '7-7': [createEvent('روز آتش‌نشانی و امنیت', false),createEvent('روز بزرگداشت شمس', false)],
    '7-8': [createEvent('روز بزرگداشت مولوی', false)],
    '7-12': [createEvent('روز وقف', false)],
    '7-13': [createEvent('روز نیروی انتظامی', false)],
    '7-14': [createEvent('روز دامپزشکی', false)],
    '7-15': [createEvent('روز روستا و عشایر', false)],
    '7-20': [createEvent('روز بزرگداشت حافظ', false)],
    '7-24': [createEvent('روز ملی پارالمپیک', false)],
    '7-26': [createEvent('روز تربیت بدنی و ورزش', false)],
    '7-29': [createEvent('روز صادرات', false)],
    '8-8': [createEvent('روز نوجوان و بسیج دانشجویی', false)],
    '8-13': [createEvent('روز دانش‌آموز', false)],
    '8-14': [createEvent('روز فرهنگ عمومی', false)],
    '8-24': [createEvent('روز کتاب، کتاب‌خوانی و کتابدار', false)],
    '9-7': [createEvent('روز نیروی دریایی', false)],
    '9-9': [createEvent('روز بزرگداشت شیخ مفید', false)],
    '9-16': [createEvent('روز دانشجو', false)],
    '9-25': [createEvent('روز پژوهش', false)],
    '9-27': [createEvent('روز وحدت حوزه و دانشگاه', false)],
    '9-30': [createEvent('شب یلدا', false)],
    '10-5': [createEvent('روز ایمنی در برابر زلزله و کاهش اثرات بلایای طبیعی', false)],
    '11-14': [createEvent('روز فناوری فضایی', false)],
    '11-19': [createEvent('روز نیروی هوایی', false)],
    '11-22': [createEvent('پیروزی انقلاب اسلامی', true)],
    '11-19': [createEvent('روز اقتصاد مقاومتی و کارآفرینی', false)],
    '12-5': [createEvent('روز بزرگداشت خواجه نصیرالدین طوسی', false),createEvent('روز مهندسی', false)],
    '12-14': [createEvent('روز احسان و نیکوکاری', false),createEvent('روز ترویج فرهنگ قرض‌الحسنه', false)],
    '12-15': [createEvent('روز درختکاری', false)],
    '12-20': [createEvent('روز راهیان نور', false)],
    '12-21': [createEvent('روز بزرگداشت نظامی گنجوی', false)],
    '12-25': [createEvent('روز بزرگداشت پروین اعتصامی', false)],
    '12-29': [createEvent('روز ملی شدن صنعت نفت', true)],
};

// Consolidated Hijri (Arabic) Events
// Sources: 
// - https://www.farhang.gov.ir/ershad_content/media/image/2020/09/1004261_orig.pdf
const HIJRI_EVENTS = {
    '1-1':[createEvent('آغاز سال جدید هجری قمری', false)],
    '1-9':[createEvent('تاسوعای حسینی', true)],
    '1-10':[createEvent('عاشورای حسینی', true)],
    '1-12':[createEvent('شهادت امام سجاد (ع)', false)],
    '2-20':[createEvent('اربعین حسینی', true)],
    '2-28':[createEvent('رحلت حضرت رسول اکرم (ص)', true),    createEvent('شهادت امام حسن مجتبی (ع)', true)],
    '2-30':[createEvent('شهادت امام رضا (ع)', true)],
    '3-1':[createEvent('هجرت حضرت رسول اکرم (ص) از مکه به مدینه', false)],
    '3-8':[createEvent('شهادت امام حسن عسکری (ع)', true)],
    '3-19':[createEvent('ولادت حضرت رسول اکرم (ص) به روایت اهل سنت', false)],
    '3-17':[createEvent('ولادت حضرت رسول اکرم (ص)', true),    createEvent('ولادت امام جعفر صادق (ع)', true)],
    '4-8':[createEvent('ولادت امام حسن عسکری (ع)', false)],
    '4-10':[createEvent('وفات حضرت معصومه (س)', false)],
    '5-5':[createEvent('ولادت حضرت زینب (س)', false),    createEvent('روز پرستار', false)],
    '6-3':[createEvent('شهادت حضرت فاطمه (س)', true)],
    '6-13':[createEvent('وفات حضرت ام‌البنین (س)', false),    createEvent('روز تکریم مادران و همسران شهدا', false)],
    '6-20':[createEvent('ولادت حضرت فاطمه (س) و روز زن', false),    createEvent('تولد حضرت امام خمینی (ره)', false)],
    '7-1':[createEvent('ولادت امام محمد باقر (ع)', false)],
    '7-3':[createEvent('شهادت امام علی نقی (ع)', false)],
    '7-10':[createEvent('ولادت امام محمد تقی (ع)', false)],
    '7-13':[createEvent('ولادت امام علی (ع)', true),    createEvent('روز پدر', true)],
    '7-15':[createEvent('ارتحال حضرت زینب (س)', false)],
    '7-25':[createEvent('شهادت امام موسی کاظم (ع)', false)],
    '7-27':[createEvent('مبعث حضرت رسول اکرم (ص)', true)],
    '8-3':[createEvent('ولادت امام حسین (ع)', false),    createEvent('روز پاسدار', false)],
    '8-4':[createEvent('ولادت ابوالفضل عباس (ع)', false),    createEvent('روز جانباز', false)],
    '8-5':[createEvent('ولادت امام سجاد (ع)', false)],
    '8-11':[createEvent('ولادت علی اکبر (ع)', false),    createEvent('روز جوان', false)],
    '8-15':[createEvent('ولادت حضرت قائم (عجل)', true),    createEvent('روز جهانی مستضعفان', true)],
    '9-15':[createEvent('ولادت امام حسن مجتبی (ع)', false),    createEvent('روز اکرام و تکریم خیرین', false)],
    '9-18':[createEvent('شب قدر', false)],
    '9-19':[createEvent('ضربت خوردن امام علی (ع)', false)],
    '9-20':[createEvent('شب قدر', false)],
    '9-21':[createEvent('شهادت حضرت علی (ع)', true)],
    '9-22':[createEvent('شب قدر', false)],
    '10-1':[createEvent('عید فطر', true)],
    '10-2':[createEvent('تعطیلات عید فطر', true)],
    '10-25':[createEvent('شهادت امام جعفر صادق (ع)', true)],
    '11-1':[createEvent('ولادت حضرت معصومه (س)', false),    createEvent('روز دختران', false)],
    '11-11':[createEvent('ولادت امام رضا (ع)', false)],
    '11-30':[createEvent('شهادت امام محمد تقی (ع)', false)],
    '12-1':[createEvent('سالروز ازدواج امام علی (ع) و حضرت فاطمه (س)', false),    createEvent('روز ازدواج', false),    createEvent('روز عفاف و حجاب', false)],
    '12-7':[createEvent('شهادت امام محمد باقر (ع)', false)],
    '12-9':[createEvent('روز عرفه', false)],
    '12-10':[createEvent('عید قربان', true)],
    '12-15':[createEvent('ولادت امام علی نقی (ع)', false)],
    '12-18':[createEvent('عید غدیر خم', true)],
    '12-20':[createEvent('ولادت امام موسی کاظم (ع)', false)],
};

// Consolidated Gregorian (International) Events
// Sources:
// - https://en.wikipedia.org/wiki/International_Days_UNESCO
const GREGORIAN_EVENTS = {
    '1-1':[createEvent('جشن آغاز سال نو میلادی', false)],
    '1-14':[createEvent('روز جهانی منطق', false),createEvent('جشن ولنتاین', false)],
    '1-24':[createEvent('روز جهانی آموزش', false),createEvent('روز جهانی فرهنگ آفریقایی', false)],
    '1-26':[createEvent('روز جهانی گمرک', false)],
    '1-27':[createEvent('روز جهانی یادبود هولوکاست', false)],
    '2-11':[createEvent('روز جهانی زنان و دختران در علم', false)],
    '2-13':[createEvent('روز جهانی رادیو', false)],
    '2-20':[createEvent('روز جهانی عدالت اجتماعی', false)],
    '2-21':[createEvent('روز جهانی زبان مادری', false)],
    '3-4':[createEvent('روز جهانی مهندسی برای توسعه پایدار', false)],
    '3-8':[createEvent('روز جهانی زن', false)],
    '3-14':[createEvent('روز جهانی ریاضیات', false)],
    '3-20':[createEvent('روز جهانی شادی', false),createEvent('روز جهانی فرانکفونی', false)],
    '3-21':[createEvent('روز جهانی نوروز', false),createEvent('روز جهانی شعر', false),createEvent('روز جهانی رفع تبعیض نژادی', false)],
    '3-22':[createEvent('روز جهانی آب', false)],
    '3-23':[createEvent('روز جهانی هواشناسی', false)],
    '3-27':[createEvent('روز جهانی تئاتر', false)],
    '4-4':[createEvent('روز جهانی ضد مین', false)],
    '4-6':[createEvent('روز جهانی ورزش برای توسعه و صلح', false)],
    '4-7':[createEvent('روز جهانی بهداشت', false)],
    '4-12':[createEvent('روز جهانی کیهان نوردی', false)],
    '4-15':[createEvent('روز جهانی هنر', false)],
    '4-22':[createEvent('روز زمین', false)],
    '4-23':[createEvent('روز جهانی کتاب', false)],
    '4-27':[createEvent('روز جهانی طراحی و گرافیک', false)],
    '4-30':[createEvent('روز جهانی جاز', false)],
    '5-1':[createEvent('روز جهانی کارگر', false)],
    '5-3':[createEvent('روز جهانی آزادی مطبوعات', false)],
    '5-5':[createEvent('روز جهانی ماما', false),createEvent('روز میراث جهانی آفریقا', false),createEvent('روز جهانی زبان پرتغالی', false)],
    '5-8':[createEvent('روز جهانی صلیب سرخ و هلال احمر', false)],
    '5-15':[createEvent('روز جهانی خانواده', false)],
    '5-16':[createEvent('روز جهانی نور', false),createEvent('روز جهانی زندگی با هم در صلح', false)],
    '5-17':[createEvent('روز جهانی ارتباطات', false)],
    '5-18':[createEvent('روز جهانی موزه و میراث فرهنگی', false)],
    '5-21':[createEvent('روز جهانی تنوع فرهنگی برای گفتگو و توسعه', false)],
    '5-22':[createEvent('روز جهانی تنوع زیستی', false)],
    '5-29':[createEvent('روز جهانی کلاه‌آبی‌های سازمان ملل', false)],
    '5-31':[createEvent('روز جهانی بدون دخانیات', false)],
    '6-4':[createEvent('روز جهانی کودکان قربانی تجاوز', false)],
    '6-5':[createEvent('روز جهانی محیط زیست', false)],
    '6-8':[createEvent('روز جهانی اقیانوس‌ها', false)],
    '6-10':[createEvent('روز جهانی صنایع دستی', false)],
    '6-12':[createEvent('روز جهانی مبارزه با کار کودکان', false)],
    '6-14':[createEvent('روز جهانی اهدای خون', false)],
    '6-17':[createEvent('روز جهانی مبارزه با بیابان و خشکسالی', false)],
    '6-20':[createEvent('روز جهانی پناهندگان', false)],
    '6-23':[createEvent('روز جهانی خدمات دولتی', false)],
    '6-26':[createEvent('روز جهانی مبارزه با مواد مخدر', false)],
    '7-11':[createEvent('روز جهانی جمعیت', false)],
    '7-18':[createEvent('روز جهانی نلسون ماندلا', false)],
    '7-26':[createEvent('روز جهانی حفاظت از اکوسیستم حرا', false)],
    '8-1':[createEvent('روز جهانی شیر مادر', false)],
    '8-9':[createEvent('روز جهانی بومیان', false)],
    '8-12':[createEvent('روز جهانی جوانان', false)],
    '8-13':[createEvent('روز جهانی چپ‌دست‌ها', false)],
    '8-19':[createEvent('روز جهانی عکاسی', false)],
    '8-23':[createEvent('روز جهانی یادآوری تجارت برده و لغو آن', false)],
    '8-31':[createEvent('روز جهانی وبلاگ', false)],
    '9-8':[createEvent('روز جهانی سوادآموزی', false)],
    '9-10':[createEvent('روز جهانی پیشگیری از خودکشی', false)],
    '9-15':[createEvent('روز جهانی مردم سالاری', false)],
    '9-16':[createEvent('روز جهانی نگه‌داری از لایه ازن', false)],
    '9-20':[createEvent('روز جهانی ورزش دانشگاهی', false)],
    '9-21':[createEvent('روز جهانی صلح', false)],
    '9-27':[createEvent('روز جهانی جهان‌گردی', false)],
    '9-28':[createEvent('روز جهانی دسترسی جهانی به اطلاعات', false)],
    '9-30':[createEvent('روز جهانی دریانوردی', false),createEvent('روز جهانی ناشنوایان', false),createEvent('روز جهانی ترجمه و مترجم', false)],
    '10-1':[createEvent('روز جهانی سالمندان', false)],
    '10-4':[createEvent('آغاز هفته جهانی فضا', false)],
    '10-5':[createEvent('روز جهانی آموزگار', false)],
    '10-8':[createEvent('روز جهانی کودک', false)],
    '10-9':[createEvent('روز جهانی پست', false)],
    '10-10':[createEvent('روز جهانی بهداشت روان', false),createEvent('روز جهانی مبارزه با حکم اعدام', false)],
    '10-11':[createEvent('روز جهانی دختر', false)],
    '10-13':[createEvent('روز جهانی کاهش بلایا', false)],
    '10-14':[createEvent('روز جهانی استاندارد', false)],
    '10-15':[createEvent('روز جهانی عصای سفید', false)],
    '10-16':[createEvent('روز جهانی غذا', false)],
    '10-17':[createEvent('روز جهانی مبارزه با فقر', false)],
    '10-24':[createEvent('روز جهانی سارمان ملل', false),createEvent('روز جهانی اخبار', false)],
    '10-27':[createEvent('روز جهانی میراث سمعی و بصری', false)],
    '11-2':[createEvent('روز جهانی پایان دادن به مصونیت از مجازات برای جنایات علیه خبرنگاران', false)],
    '11-5':[createEvent('روز جهانی زبان رومی', false),createEvent('روز جهانی آگاهی از سونامی', false)],
    '11-10':[createEvent('روز جهانی علم در خدمت صلح و توسعه پایدار', false)],
    '11-14':[createEvent('روز جهانی دیابت', false),createEvent('روز جهانی مبارزه با قاچاق غیرقانونی اموال فرهنگی', false)],
    '11-16':[createEvent('روز جهانی مدارا', false)],
    '11-18':[createEvent('روز جهانی هنر اسلامی', false),createEvent('روز جهانی فلسفه', false)],
    '11-19':[createEvent('روز جهانی آقایان', false)],
    '11-21':[createEvent('روز جهانی تلویزیون', false)],
    '11-25':[createEvent('روز جهانی مبارزه با خشونت علیه زنان', false)],
    '11-26':[createEvent('روز جهانی درخت زیتون', false)],
    '11-29':[createEvent('روز جهانی همبستگی با مردم فلسطین', false)],
    '12-1':[createEvent('روز جهانی ایدز', false)],
    '12-2':[createEvent('روز جهانی آزادی بردگان', false)],
    '12-3':[createEvent('روز جهانی افراد دارای معلولیت', false)],
    '12-7':[createEvent('روز جهانی هواپیمایی', false)],
    '12-10':[createEvent('روز جهانی حقوق بشر', false)],
    '12-11':[createEvent('روز جهانی کوه‌نوردی', false)],
    '12-18':[createEvent('روز جهانی مهاجرین', false),createEvent('روز جهانی زبان عربی', false)],
    '12-25':[createEvent('جشن کریسمس', false)],
    '12-30':[createEvent('روز جهانی همبستگی انسانی', false)],
};

export function getEventsForDate(date) {
    const j = Jalaali.toJalaali(date);
    const h = Jalaali.toHijri(date);
    const gDay = date.getDate();
    const gMonth = date.getMonth() + 1;

    const events = [];

    const sEvents = IRANIAN_EVENTS[`${j.jm}-${j.jd}`] || [];
    const lEvents = HIJRI_EVENTS[`${h.jm}-${h.jd}`] || [];
    const grEvents = GREGORIAN_EVENTS[`${gMonth}-${gDay}`] || [];

    return [...sEvents, ...lEvents, ...grEvents];
}
